version: '2'
volumes:
  database: {}
  temp: {}
services:
  nginx:
    extends:
      file: base.yml
      service: service
    image: raybird/dockernginx
    ports:
      - "18080:80"
    links:
      - php
    logging:
      driver: syslog
      options:
        tag: "playground-http"
  php:
    extends:
      file: base.yml
      service: service
    image: raybird/dockerphp7fpm
    links:
      - mysql
    logging:
      driver: syslog
      options:
        tag: "playground-php"
  mysql:
    extends:
      file: base.yml
      service: service
    image: mysql:latest
    ports:
      - 3306:3306
# phpmyadmin for develop
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
    env_file: .env
    environment:
      PMA_HOST: mysql
    ports:
      - "18081:80"